# -*- coding: utf-8 -*-
"""DesafioTec.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vmw82CZAxzYy7g3K1_bT2fzf-vS5S2l2

Instalação da biblioteca WorldfootballR
"""

install.packages("devtools")
install.packages("remotes")
devtools::install_github("JaseZiv/worldfootballR")

library(worldfootballR)

"""Teste das medidas originais

"""

tm_team_player_urls(team_url = "https://www.transfermarkt.com.br/se-palmeiras/leistungsdaten/verein/1023/plus/1?reldata=BCP1%262024")

team_urls <- tm_league_team_urls(country_name = "Brazil", start_year = 2024)

team_urls

epl_team_players_2020 <- tm_squad_stats(team_url = team_urls)

epl_team_players_2020

team<-  'https://www.transfermarkt.com.br/cr-flamengo/leistungsdaten/verein/614/reldata/%262025/plus/1'

teste<-tm_squad_stats(team_url = team)

teste

league_one_teams <- tm_league_team_urls(start_year = 2024, league_url = "https://www.transfermarkt.com.br/campeonato-paulista-serie-a1-grunddurchgang/teilnehmer/pokalwettbewerb/BCP1/saison_id/2024")

league_one_teams

epl_team_players_2020 <- tm_squad_stats(team_url = league_one_teams)

epl_team_players_2020

"""Código para adaptar Urls dos times do Paulistão 2025 para levarem a página de dados detalhados

"""

urls_novas <- gsub(
  "startseite",
  "leistungsdaten",
  league_one_teams
)

urls_novas <- paste0(
  urls_novas,
  "/reldata/BCP1%262024/plus/1"
)

urls_novas

testepaulista<- tm_squad_stats(team_url = urls_novas)

testepaulista

write.csv(testepaulista, "paulista.csv", row.names = FALSE)

link<-'https://www.transfermarkt.com/se-palmeiras-sao-paulo/leistungsdaten/verein/1023/reldata/BCP1%262024/plus/1'

teste<-tm_squad_stats(team_url = link)

tm_squad_stats("https://www.transfermarkt.com/portuguesa-sao-paulo/startseite/verein/10247/saison_id/2025")

"""Primeira Adaptação da função tm_squad_stats"""

#' Get detailed squad player stats
#'
#' Returns detailed stats for players of a team season including assists
#'
#' @param team_url transfermarkt.com team url for a season
#'
#' @return returns a dataframe of all player stats for team(s) with detailed statistics
#'
#' @importFrom magrittr %>%
#' @importFrom rlang .data
#'
#' @export
tm_squad_stats_detailed <- function(team_url) {

  main_url <- "https://www.transfermarkt.com"

  each_squad_stats <- function(each_team_url) {
    pb$tick()

    # Convert startseite URL to leistungsdaten URL
    team_data_url <- gsub("startseite", "leistungsdaten", each_team_url)
    # Add /plus/1 to get detailed view with more columns
    if(!grepl("plus/", team_data_url)) {
      team_data_url <- paste0(team_data_url, "/plus/1")
    }

    team_data_page <- tryCatch(xml2::read_html(team_data_url), error = function(e) NA)

    if(!is.na(team_data_page)) {

      # Get team info
      team_name <- team_data_page %>%
        rvest::html_nodes(".data-header__headline-wrapper--oswald") %>%
        rvest::html_text() %>%
        stringr::str_squish()
      if(length(team_name) == 0) team_name <- NA_character_

      # League - handle empty case
      league <- team_data_page %>%
        rvest::html_nodes(".data-header__club a") %>%
        rvest::html_text() %>%
        stringr::str_squish()
      if(length(league) == 0) league <- NA_character_

      country <- team_data_page %>%
        rvest::html_nodes(".vm") %>%
        rvest::html_attr("title")
      if(length(country) == 0) country <- NA_character_

      # Get all data rows
      data_rows <- team_data_page %>%
        rvest::html_nodes("#yw1 .items tbody tr.odd, #yw1 .items tbody tr.even")

      if(length(data_rows) == 0) {
        data_rows <- team_data_page %>%
          rvest::html_nodes("table.items tbody tr")
      }

      if(length(data_rows) == 0) {
        return(data.frame())
      }

      # Extract data from each row
      player_data_list <- list()

      for(i in seq_along(data_rows)) {
        row <- data_rows[i]

        # Get all cells in this row
        cells <- row %>% rvest::html_nodes("td")

        if(length(cells) >= 12) {

          # Helper function to clean text
          clean_text <- function(text) {
            if(length(text) == 0) return(NA_character_)
            text <- text %>% stringr::str_squish()
            if(text == "" || text == "-") return(NA_character_)
            return(text)
          }

          # Helper function to extract numeric value
          extract_number <- function(cell, default = 0) {
            if(length(cell) == 0) return(default)
            text <- cell %>% rvest::html_text() %>% stringr::str_squish()
            if(length(text) == 0 || is.na(text) || text == "" || text == "-") return(default)
            # Handle special text values
            if(grepl("Not in squad|Not used", text)) return(0)
            # Remove non-numeric characters except decimal
            num_text <- stringr::str_extract(text, "\\d+\\.?\\d*")
            if(is.na(num_text)) return(default)
            result <- suppressWarnings(as.numeric(num_text))
            if(is.na(result)) return(default)
            return(result)
          }

          # Extract player name from col 2
          col2_text <- cells[2] %>% rvest::html_text() %>% stringr::str_squish()
          player_name <- NA_character_
          player_url <- NA_character_

          # Try to extract name from col 2 (format: "NameNamePosition")
          # Look for pattern where name repeats
          if(!is.na(col2_text) && col2_text != "") {
            # Try to find the first occurrence of a capital letter pattern
            # Many names have format like "Rafael SantosRafael SantosGoalkeeper"
            name_match <- stringr::str_match(col2_text, "^([A-Za-zÀ-ÿ\\s]+?)\\1")
            if(!is.na(name_match[1,2])) {
              player_name <- stringr::str_squish(name_match[1,2])
            } else {
              # If no repeat, try to extract just the name part
              player_name <- stringr::str_extract(col2_text, "^[A-Za-zÀ-ÿ]+(?:\\s+[A-Za-zÀ-ÿ]+)*")
              if(is.na(player_name)) player_name <- col2_text
            }
          }

          # Also try to get URL from col 2 links
          links <- cells[2] %>% rvest::html_nodes("a")
          if(length(links) > 0) {
            for(link in links) {
              href <- link %>% rvest::html_attr("href")
              if(!is.null(href) && grepl("/profil/spieler/", href)) {
                player_url <- paste0(main_url, href)
                # Also get clean name from link if available
                link_name <- link %>% rvest::html_text() %>% stringr::str_squish()
                if(!is.na(link_name) && link_name != "") {
                  player_name <- link_name
                }
                break
              }
            }
          }

          # Skip if no player name
          if(is.na(player_name) || player_name == "" || nchar(player_name) < 2) next

          # Extract position from col 5
          player_pos <- NA_character_
          if(length(cells) >= 5) {
            player_pos <- clean_text(cells[5] %>% rvest::html_text())
          }

          # Extract age from col 6
          player_age <- NA_real_
          if(length(cells) >= 6) {
            player_age <- extract_number(cells[6])
            if(player_age == 0) player_age <- NA_real_
          }

          # Extract nationality from col 4 (flags)
          nationality <- NA_character_
          if(length(cells) >= 4) {
            flags <- cells[4] %>% rvest::html_nodes("img")
            if(length(flags) > 0) {
              nationality <- flags[1] %>% rvest::html_attr("title")
            }
          }

          # Extract stats based on actual column mapping from debug:
          # Col 8: In squad
          # Col 9: Appearances
          # Col 10: Goals
          # Col 11: Assists
          # Col 17-18: Minutes played

          in_squad <- if(length(cells) >= 8) extract_number(cells[8]) else 0
          appearances <- if(length(cells) >= 9) extract_number(cells[9]) else 0
          goals <- if(length(cells) >= 10) extract_number(cells[10]) else 0
          assists <- if(length(cells) >= 11) extract_number(cells[11]) else 0

          # Minutes played - look in col 18 first (has apostrophe format), then col 17
          minutes_played <- NA_real_
          if(length(cells) >= 18) {
            minutes_text <- cells[18] %>% rvest::html_text() %>% stringr::str_squish()
            if(!is.na(minutes_text) && minutes_text != "" && minutes_text != "-") {
              minutes_clean <- minutes_text %>%
                gsub("\\.", "", .) %>%
                gsub("'", "", .) %>%
                gsub(",", "", .)
              minutes_num <- suppressWarnings(as.numeric(minutes_clean))
              if(!is.na(minutes_num) && minutes_num > 0) {
                minutes_played <- minutes_num
              }
            }
          }

          # If no minutes in col 18, try col 17
          if(is.na(minutes_played) && length(cells) >= 17) {
            minutes_text <- cells[17] %>% rvest::html_text() %>% stringr::str_squish()
            if(!is.na(minutes_text) && minutes_text != "" && minutes_text != "-") {
              # Skip if it looks like PPG (decimal between 0-3)
              minutes_num <- suppressWarnings(as.numeric(minutes_text))
              if(!is.na(minutes_num) && (minutes_num > 3 || minutes_num < 0.5)) {
                minutes_clean <- minutes_text %>%
                  gsub("\\.", "", .) %>%
                  gsub("'", "", .)
                minutes_num <- suppressWarnings(as.numeric(minutes_clean))
                if(!is.na(minutes_num) && minutes_num > 0) {
                  minutes_played <- minutes_num
                }
              }
            }
          }

          player_data_list[[i]] <- data.frame(
            team_name = team_name,
            league = league,
            country = country,
            player_name = player_name,
            player_url = player_url,
            player_pos = player_pos,
            player_age = player_age,
            nationality = nationality,
            in_squad = in_squad,
            appearances = appearances,
            goals = goals,
            assists = assists,
            minutes_played = minutes_played,
            stringsAsFactors = FALSE
          )
        }
      }

      # Combine all player data
      if(length(player_data_list) > 0) {
        team_data_df <- dplyr::bind_rows(player_data_list)

        # Remove duplicate rows
        if("player_url" %in% names(team_data_df) && !all(is.na(team_data_df$player_url))) {
          team_data_df <- team_data_df %>%
            dplyr::distinct(player_url, .keep_all = TRUE)
        }
      } else {
        team_data_df <- data.frame()
      }

    } else {
      team_data_df <- data.frame()
    }

    return(team_data_df)

  }

  # create the progress bar with a progress function.
  pb <- progress::progress_bar$new(total = length(team_url))

  f_possibly <- purrr::possibly(each_squad_stats, otherwise = data.frame(), quiet = FALSE)
  purrr::map_dfr(
    team_url,
    f_possibly
  )

}

"""Segunda adaptação

"""

#' Get detailed squad player stats
#'
#' Returns detailed stats for players of a team season including assists
#'
#' @param team_url transfermarkt.com team url for a season
#'
#' @return returns a dataframe of all player stats for team(s) with detailed statistics
#'
#' @importFrom magrittr %>%
#' @importFrom rlang .data
#'
#' @export
tm_squad_stats_detailed <- function(team_url) {

  main_url <- "https://www.transfermarkt.com"

  each_squad_stats <- function(each_team_url) {
    pb$tick()

    # Convert startseite URL to leistungsdaten URL
    team_data_url <- gsub("startseite", "leistungsdaten", each_team_url)
    # Add /plus/1 to get detailed view with more columns
    if(!grepl("plus/", team_data_url)) {
      team_data_url <- paste0(team_data_url, "/plus/1")
    }

    team_data_page <- tryCatch(xml2::read_html(team_data_url), error = function(e) NA)

    if(!is.na(team_data_page)) {

      # Get team info
      team_name <- team_data_page %>%
        rvest::html_nodes(".data-header__headline-wrapper--oswald") %>%
        rvest::html_text() %>%
        stringr::str_squish()
      if(length(team_name) == 0) team_name <- NA_character_

      # League - handle empty case
      league <- team_data_page %>%
        rvest::html_nodes(".data-header__club a") %>%
        rvest::html_text() %>%
        stringr::str_squish()
      if(length(league) == 0) league <- NA_character_

      country <- team_data_page %>%
        rvest::html_nodes(".vm") %>%
        rvest::html_attr("title")
      if(length(country) == 0) country <- NA_character_

      # Get all data rows
      data_rows <- team_data_page %>%
        rvest::html_nodes("#yw1 .items tbody tr.odd, #yw1 .items tbody tr.even")

      if(length(data_rows) == 0) {
        data_rows <- team_data_page %>%
          rvest::html_nodes("table.items tbody tr")
      }

      if(length(data_rows) == 0) {
        return(data.frame())
      }

      # Extract data from each row
      player_data_list <- list()

      for(i in seq_along(data_rows)) {
        row <- data_rows[i]

        # Get all cells in this row
        cells <- row %>% rvest::html_nodes("td")

        if(length(cells) >= 12) {

          # Helper function to clean text
          clean_text <- function(text) {
            if(length(text) == 0) return(NA_character_)
            text <- text %>% stringr::str_squish()
            if(text == "" || text == "-") return(NA_character_)
            return(text)
          }

          # Helper function to extract numeric value
          extract_number <- function(cell, default = 0) {
            if(length(cell) == 0) return(default)
            text <- cell %>% rvest::html_text() %>% stringr::str_squish()
            if(length(text) == 0 || is.na(text) || text == "" || text == "-") return(default)
            # Handle special text values
            if(grepl("Not in squad|Not used", text)) return(0)
            # Remove non-numeric characters except decimal
            num_text <- stringr::str_extract(text, "\\d+\\.?\\d*")
            if(is.na(num_text)) return(default)
            result <- suppressWarnings(as.numeric(num_text))
            if(is.na(result)) return(default)
            return(result)
          }

          # Extract player name from the second cell (column 2)
          player_name <- NA_character_
          player_url <- NA_character_

          if(length(cells) >= 2) {
            # Look for the player profile link in column 2
            player_link <- cells[2] %>% rvest::html_nodes("a[href*='/profil/spieler/']")
            if(length(player_link) > 0) {
              # Get the first valid player link
              for(link in player_link) {
                href <- link %>% rvest::html_attr("href")
                if(!is.null(href) && grepl("/profil/spieler/", href)) {
                  player_url <- paste0(main_url, href)
                  player_name <- link %>% rvest::html_text() %>% stringr::str_squish()
                  if(!is.na(player_name) && player_name != "") {
                    break
                  }
                }
              }
            }
          }

          # Skip if no player name
          if(is.na(player_name) || player_name == "" || nchar(player_name) < 2) next

          # Extract position from column 5
          player_pos <- NA_character_
          if(length(cells) >= 5) {
            player_pos <- clean_text(cells[5] %>% rvest::html_text())
          }

          # Extract age from column 6
          player_age <- NA_real_
          if(length(cells) >= 6) {
            player_age <- extract_number(cells[6])
            if(player_age == 0) player_age <- NA_real_
          }

          # Extract nationality from column 4 - FIXED based on the flag image structure
          nationality <- NA_character_
          if(length(cells) >= 4) {
            # Look for flag images with class "flaggenrahmen"
            flags <- cells[4] %>% rvest::html_nodes("img.flaggenrahmen")

            if(length(flags) > 0) {
              # Try to get alt attribute first (most common for country names)
              flag_alt <- flags[1] %>% rvest::html_attr("alt")
              if(!is.na(flag_alt) && flag_alt != "" && nchar(flag_alt) > 0) {
                nationality <- flag_alt
              }

              # If alt is empty, try title attribute
              if(is.na(nationality) || nationality == "") {
                flag_title <- flags[1] %>% rvest::html_attr("title")
                if(!is.na(flag_title) && flag_title != "" && nchar(flag_title) > 0) {
                  nationality <- flag_title
                }
              }

              # If still no nationality, try to get from the cell's name attribute (as seen in your accessibility tree)
              if(is.na(nationality) || nationality == "") {
                cell_name <- cells[4] %>% rvest::html_attr("name")
                if(!is.na(cell_name) && cell_name != "" && nchar(cell_name) > 0) {
                  nationality <- cell_name
                }
              }
            }

            # If no flag found, try to get from any image in column 4
            if(is.na(nationality) || nationality == "") {
              any_img <- cells[4] %>% rvest::html_nodes("img")
              if(length(any_img) > 0) {
                img_alt <- any_img[1] %>% rvest::html_attr("alt")
                if(!is.na(img_alt) && img_alt != "" && nchar(img_alt) > 0) {
                  nationality <- img_alt
                }
              }
            }
          }

          # Extract stats based on column mapping:
          # Based on debug output:
          # Col 8: In squad
          # Col 9: Appearances
          # Col 10: Goals
          # Col 11: Assists
          # Col 18: Minutes played

          in_squad <- if(length(cells) >= 8) extract_number(cells[8]) else 0
          appearances <- if(length(cells) >= 9) extract_number(cells[9]) else 0
          goals <- if(length(cells) >= 10) extract_number(cells[10]) else 0
          assists <- if(length(cells) >= 11) extract_number(cells[11]) else 0

          # Minutes played - look in col 18 first (has apostrophe format)
          minutes_played <- NA_real_
          if(length(cells) >= 18) {
            minutes_text <- cells[18] %>% rvest::html_text() %>% stringr::str_squish()
            if(!is.na(minutes_text) && minutes_text != "" && minutes_text != "-") {
              minutes_clean <- minutes_text %>%
                gsub("\\.", "", .) %>%
                gsub("'", "", .) %>%
                gsub(",", "", .)
              minutes_num <- suppressWarnings(as.numeric(minutes_clean))
              if(!is.na(minutes_num) && minutes_num > 0) {
                minutes_played <- minutes_num
              }
            }
          }

          # If no minutes in col 18, try col 17
          if(is.na(minutes_played) && length(cells) >= 17) {
            minutes_text <- cells[17] %>% rvest::html_text() %>% stringr::str_squish()
            if(!is.na(minutes_text) && minutes_text != "" && minutes_text != "-") {
              # Skip if it looks like PPG (decimal between 0-3)
              minutes_num <- suppressWarnings(as.numeric(minutes_text))
              if(!is.na(minutes_num) && (minutes_num > 3 || minutes_num < 0.5)) {
                minutes_clean <- minutes_text %>%
                  gsub("\\.", "", .) %>%
                  gsub("'", "", .)
                minutes_num <- suppressWarnings(as.numeric(minutes_clean))
                if(!is.na(minutes_num) && minutes_num > 0) {
                  minutes_played <- minutes_num
                }
              }
            }
          }

          player_data_list[[i]] <- data.frame(
            team_name = team_name,
            league = league,
            country = country,
            player_name = player_name,
            player_url = player_url,
            player_pos = player_pos,
            player_age = player_age,
            nationality = nationality,
            in_squad = in_squad,
            appearances = appearances,
            goals = goals,
            assists = assists,
            minutes_played = minutes_played,
            stringsAsFactors = FALSE
          )
        }
      }

      # Combine all player data
      if(length(player_data_list) > 0) {
        team_data_df <- dplyr::bind_rows(player_data_list)

        # Remove duplicate rows
        if("player_url" %in% names(team_data_df) && !all(is.na(team_data_df$player_url))) {
          team_data_df <- team_data_df %>%
            dplyr::distinct(player_url, .keep_all = TRUE)
        }
      } else {
        team_data_df <- data.frame()
      }

    } else {
      team_data_df <- data.frame()
    }

    return(team_data_df)

  }

  # create the progress bar with a progress function.
  pb <- progress::progress_bar$new(total = length(team_url))

  f_possibly <- purrr::possibly(each_squad_stats, otherwise = data.frame(), quiet = FALSE)
  purrr::map_dfr(
    team_url,
    f_possibly
  )

}

"""Terceira Adaptação:

preencher nacionalidade a partir da página do jogador


"""

#' Get detailed squad player stats
#'
#' Returns detailed stats for players of a team season including assists
#'
#' @param team_url transfermarkt.com team url for a season
#'
#' @return returns a dataframe of all player stats for team(s) with detailed statistics
#'
#' @importFrom magrittr %>%
#' @importFrom rlang .data
#'
#' @export
tm_squad_stats_detailed <- function(team_url) {

  main_url <- "https://www.transfermarkt.com"

  each_squad_stats <- function(each_team_url) {
    pb$tick()

    # Convert startseite URL to leistungsdaten URL
    team_data_url <- gsub("startseite", "leistungsdaten", each_team_url)
    # Add /plus/1 to get detailed view with more columns
    if(!grepl("plus/", team_data_url)) {
      team_data_url <- paste0(team_data_url, "/plus/1")
    }

    team_data_page <- tryCatch(xml2::read_html(team_data_url), error = function(e) NA)

    if(!is.na(team_data_page)) {

      # Get team info
      team_name <- team_data_page %>%
        rvest::html_nodes(".data-header__headline-wrapper--oswald") %>%
        rvest::html_text() %>%
        stringr::str_squish()
      if(length(team_name) == 0) team_name <- NA_character_

      # League - handle empty case
      league <- team_data_page %>%
        rvest::html_nodes(".data-header__club a") %>%
        rvest::html_text() %>%
        stringr::str_squish()
      if(length(league) == 0) league <- NA_character_

      country <- team_data_page %>%
        rvest::html_nodes(".vm") %>%
        rvest::html_attr("title")
      if(length(country) == 0) country <- NA_character_

      # Get all data rows
      data_rows <- team_data_page %>%
        rvest::html_nodes("#yw1 .items tbody tr.odd, #yw1 .items tbody tr.even")

      if(length(data_rows) == 0) {
        data_rows <- team_data_page %>%
          rvest::html_nodes("table.items tbody tr")
      }

      if(length(data_rows) == 0) {
        return(data.frame())
      }

      # Extract data from each row
      player_data_list <- list()

      for(i in seq_along(data_rows)) {
        row <- data_rows[i]

        # Get all cells in this row
        cells <- row %>% rvest::html_nodes("td")

        if(length(cells) >= 12) {

          # Helper function to clean text
          clean_text <- function(text) {
            if(length(text) == 0) return(NA_character_)
            text <- text %>% stringr::str_squish()
            if(text == "" || text == "-") return(NA_character_)
            return(text)
          }

          # Helper function to extract numeric value
          extract_number <- function(cell, default = 0) {
            if(length(cell) == 0) return(default)
            text <- cell %>% rvest::html_text() %>% stringr::str_squish()
            if(length(text) == 0 || is.na(text) || text == "" || text == "-") return(default)
            # Handle special text values
            if(grepl("Not in squad|Not used", text)) return(0)
            # Remove non-numeric characters except decimal
            num_text <- stringr::str_extract(text, "\\d+\\.?\\d*")
            if(is.na(num_text)) return(default)
            result <- suppressWarnings(as.numeric(num_text))
            if(is.na(result)) return(default)
            return(result)
          }

          # Extract player name and URL from the second cell (column 2)
          player_name <- NA_character_
          player_url <- NA_character_

          if(length(cells) >= 2) {
            # Look for the player profile link in column 2
            player_link <- cells[2] %>% rvest::html_nodes("a[href*='/profil/spieler/']")
            if(length(player_link) > 0) {
              # Get the first valid player link
              for(link in player_link) {
                href <- link %>% rvest::html_attr("href")
                if(!is.null(href) && grepl("/profil/spieler/", href)) {
                  player_url <- paste0(main_url, href)
                  player_name <- link %>% rvest::html_text() %>% stringr::str_squish()
                  if(!is.na(player_name) && player_name != "") {
                    break
                  }
                }
              }
            }
          }

          # Skip if no player name
          if(is.na(player_name) || player_name == "" || nchar(player_name) < 2) next

          # Extract position from column 5
          player_pos <- NA_character_
          if(length(cells) >= 5) {
            player_pos <- clean_text(cells[5] %>% rvest::html_text())
          }

          # Extract age from column 6
          player_age <- NA_real_
          if(length(cells) >= 6) {
            player_age <- extract_number(cells[6])
            if(player_age == 0) player_age <- NA_real_
          }

          # Extract nationality from the player's profile page
          nationality <- NA_character_
          if(!is.na(player_url) && player_url != "") {
            # Fetch the player's profile page
            player_page <- tryCatch(xml2::read_html(player_url), error = function(e) NA)

            if(!is.na(player_page)) {
              # Look for nationality information
              # Method 1: Look for the flag image in the player header
              flag_img <- player_page %>%
                rvest::html_nodes(".data-header__items img") %>%
                .[1]

              if(length(flag_img) > 0) {
                nationality <- flag_img %>% rvest::html_attr("title")
                if(is.na(nationality) || nationality == "") {
                  nationality <- flag_img %>% rvest::html_attr("alt")
                }
              }

              # Method 2: Look for the citizenship text in the info row
              if(is.na(nationality) || nationality == "") {
                citizenship_text <- player_page %>%
                  rvest::html_nodes(".data-header__info-item") %>%
                  rvest::html_text()

                if(length(citizenship_text) > 0) {
                  # Look for text containing "Citizenship:" or similar
                  citizenship_line <- grep("Citizenship:", citizenship_text, value = TRUE, ignore.case = TRUE)
                  if(length(citizenship_line) > 0) {
                    nationality <- stringr::str_extract(citizenship_line, "Citizenship:\\s*([A-Za-zÀ-ÿ\\s]+)") %>%
                      stringr::str_replace("Citizenship:\\s*", "") %>%
                      stringr::str_squish()
                  }
                }
              }

              # Method 3: Look for the nationality in the info table
              if(is.na(nationality) || nationality == "") {
                info_table <- player_page %>%
                  rvest::html_nodes(".info-table")

                if(length(info_table) > 0) {
                  rows <- info_table %>% rvest::html_nodes("tr")
                  for(row in rows) {
                    header <- row %>% rvest::html_nodes("th") %>% rvest::html_text()
                    if(length(header) > 0 && grepl("Citizenship|Nationality", header, ignore.case = TRUE)) {
                      value <- row %>% rvest::html_nodes("td") %>% rvest::html_text() %>% stringr::str_squish()
                      if(length(value) > 0 && value != "") {
                        nationality <- value
                        break
                      }
                    }
                  }
                }
              }

              # Method 4: Look for the flag in the player info section
              if(is.na(nationality) || nationality == "") {
                flags <- player_page %>%
                  rvest::html_nodes(".info-table img")

                if(length(flags) > 0) {
                  for(flag in flags) {
                    flag_title <- flag %>% rvest::html_attr("title")
                    if(!is.na(flag_title) && flag_title != "") {
                      nationality <- flag_title
                      break
                    }
                  }
                }
              }
            }
          }

          # Extract stats based on column mapping:
          # Col 8: In squad
          # Col 9: Appearances
          # Col 10: Goals
          # Col 11: Assists
          # Col 18: Minutes played

          in_squad <- if(length(cells) >= 8) extract_number(cells[8]) else 0
          appearances <- if(length(cells) >= 9) extract_number(cells[9]) else 0
          goals <- if(length(cells) >= 10) extract_number(cells[10]) else 0
          assists <- if(length(cells) >= 11) extract_number(cells[11]) else 0

          # Minutes played - look in col 18 first (has apostrophe format)
          minutes_played <- NA_real_
          if(length(cells) >= 18) {
            minutes_text <- cells[18] %>% rvest::html_text() %>% stringr::str_squish()
            if(!is.na(minutes_text) && minutes_text != "" && minutes_text != "-") {
              minutes_clean <- minutes_text %>%
                gsub("\\.", "", .) %>%
                gsub("'", "", .) %>%
                gsub(",", "", .)
              minutes_num <- suppressWarnings(as.numeric(minutes_clean))
              if(!is.na(minutes_num) && minutes_num > 0) {
                minutes_played <- minutes_num
              }
            }
          }

          # If no minutes in col 18, try col 17
          if(is.na(minutes_played) && length(cells) >= 17) {
            minutes_text <- cells[17] %>% rvest::html_text() %>% stringr::str_squish()
            if(!is.na(minutes_text) && minutes_text != "" && minutes_text != "-") {
              # Skip if it looks like PPG (decimal between 0-3)
              minutes_num <- suppressWarnings(as.numeric(minutes_text))
              if(!is.na(minutes_num) && (minutes_num > 3 || minutes_num < 0.5)) {
                minutes_clean <- minutes_text %>%
                  gsub("\\.", "", .) %>%
                  gsub("'", "", .)
                minutes_num <- suppressWarnings(as.numeric(minutes_clean))
                if(!is.na(minutes_num) && minutes_num > 0) {
                  minutes_played <- minutes_num
                }
              }
            }
          }

          player_data_list[[i]] <- data.frame(
            team_name = team_name,
            league = league,
            country = country,
            player_name = player_name,
            player_url = player_url,
            player_pos = player_pos,
            player_age = player_age,
            nationality = nationality,
            in_squad = in_squad,
            appearances = appearances,
            goals = goals,
            assists = assists,
            minutes_played = minutes_played,
            stringsAsFactors = FALSE
          )
        }
      }

      # Combine all player data
      if(length(player_data_list) > 0) {
        team_data_df <- dplyr::bind_rows(player_data_list)

        # Remove duplicate rows
        if("player_url" %in% names(team_data_df) && !all(is.na(team_data_df$player_url))) {
          team_data_df <- team_data_df %>%
            dplyr::distinct(player_url, .keep_all = TRUE)
        }
      } else {
        team_data_df <- data.frame()
      }

    } else {
      team_data_df <- data.frame()
    }

    return(team_data_df)

  }

  # create the progress bar with a progress function.
  pb <- progress::progress_bar$new(total = length(team_url))

  f_possibly <- purrr::possibly(each_squad_stats, otherwise = data.frame(), quiet = FALSE)
  purrr::map_dfr(
    team_url,
    f_possibly
  )

}

teste<-tm_squad_stats_detailed(link)

teste

"""Repositório WORLDFOOTBALLR - https://github.com/JaseZiv/worldfootballR/blob/main/R/tm_squad_stats.R

Documentação - https://jaseziv.github.io/worldfootballR/articles/extract-transfermarkt-data.html
"""

teste<-tm_squad_stats_detailed(urls_novas)

"""Adaptação Final: Dados sobre substituições e disciplina

"""

# First, install all required packages if you haven't already
install.packages(c("magrittr", "rvest", "xml2", "stringr", "dplyr", "purrr", "progress"))

# Then load all libraries
library(magrittr)
library(rvest)
library(xml2)
library(stringr)
library(dplyr)
library(purrr)
library(progress)

# Now run the function
tm_squad_stats_detailed <- function(team_url) {

  main_url <- "https://www.transfermarkt.com"

  # Function to extract nationality from player page
  extract_nationality <- function(player_url) {
    if(is.na(player_url) || player_url == "") return(NA_character_)

    player_page <- tryCatch(xml2::read_html(player_url), error = function(e) NA)

    if(!is.na(player_page)) {
      # Look for the flag image in the player header
      flag_img <- player_page %>%
        rvest::html_nodes(".data-header__items img") %>%
        .[1]

      if(length(flag_img) > 0) {
        nationality <- flag_img %>% rvest::html_attr("title")
        if(is.na(nationality) || nationality == "") {
          nationality <- flag_img %>% rvest::html_attr("alt")
        }
        if(!is.na(nationality) && nationality != "") return(nationality)
      }

      # Look for the citizenship text in the info row
      citizenship_text <- player_page %>%
        rvest::html_nodes(".data-header__info-item") %>%
        rvest::html_text()

      if(length(citizenship_text) > 0) {
        citizenship_line <- grep("Citizenship:", citizenship_text, value = TRUE, ignore.case = TRUE)
        if(length(citizenship_line) > 0) {
          nationality <- stringr::str_extract(citizenship_line, "Citizenship:\\s*([A-Za-zÀ-ÿ\\s]+)") %>%
            stringr::str_replace("Citizenship:\\s*", "") %>%
            stringr::str_squish()
          if(!is.na(nationality) && nationality != "") return(nationality)
        }
      }

      # Look for the nationality in the info table
      info_table <- player_page %>%
        rvest::html_nodes(".info-table")

      if(length(info_table) > 0) {
        rows <- info_table %>% rvest::html_nodes("tr")
        for(row in rows) {
          header <- row %>% rvest::html_nodes("th") %>% rvest::html_text()
          if(length(header) > 0 && grepl("Citizenship|Nationality", header, ignore.case = TRUE)) {
            value <- row %>% rvest::html_nodes("td") %>% rvest::html_text() %>% stringr::str_squish()
            if(length(value) > 0 && value != "") {
              return(value)
            }
          }
        }
      }
    }

    return(NA_character_)
  }

  each_squad_stats <- function(each_team_url) {
    pb$tick()

    # Convert startseite URL to leistungsdaten URL
    team_data_url <- gsub("startseite", "leistungsdaten", each_team_url)
    # Add /plus/1 to get detailed view with more columns
    if(!grepl("plus/", team_data_url)) {
      team_data_url <- paste0(team_data_url, "/plus/1")
    }

    team_data_page <- tryCatch(xml2::read_html(team_data_url), error = function(e) NA)

    if(!is.na(team_data_page)) {

      # Get team info
      team_name <- team_data_page %>%
        rvest::html_nodes(".data-header__headline-wrapper--oswald") %>%
        rvest::html_text() %>%
        stringr::str_squish()
      if(length(team_name) == 0) team_name <- NA_character_

      # League - handle empty case
      league <- team_data_page %>%
        rvest::html_nodes(".data-header__club a") %>%
        rvest::html_text() %>%
        stringr::str_squish()
      if(length(league) == 0) league <- NA_character_

      country <- team_data_page %>%
        rvest::html_nodes(".vm") %>%
        rvest::html_attr("title")
      if(length(country) == 0) country <- NA_character_

      # Get all data rows
      data_rows <- team_data_page %>%
        rvest::html_nodes("#yw1 .items tbody tr.odd, #yw1 .items tbody tr.even")

      if(length(data_rows) == 0) {
        data_rows <- team_data_page %>%
          rvest::html_nodes("table.items tbody tr")
      }

      if(length(data_rows) == 0) {
        return(data.frame())
      }

      # Extract data from each row
      player_data_list <- list()

      for(i in seq_along(data_rows)) {
        row <- data_rows[i]

        # Get all cells in this row
        cells <- row %>% rvest::html_nodes("td")

        if(length(cells) >= 12) {

          # Helper function to clean text
          clean_text <- function(text) {
            if(length(text) == 0) return(NA_character_)
            text <- text %>% stringr::str_squish()
            if(text == "" || text == "-") return(NA_character_)
            return(text)
          }

          # Helper function to extract numeric value
          extract_number <- function(cell, default = 0) {
            if(length(cell) == 0) return(default)
            text <- cell %>% rvest::html_text() %>% stringr::str_squish()
            if(length(text) == 0 || is.na(text) || text == "" || text == "-") return(default)
            # Handle special text values
            if(grepl("Not in squad|Not used", text)) return(0)
            # Remove non-numeric characters except decimal
            num_text <- stringr::str_extract(text, "\\d+\\.?\\d*")
            if(is.na(num_text)) return(default)
            result <- suppressWarnings(as.numeric(num_text))
            if(is.na(result)) return(default)
            return(result)
          }

          # Extract player name and URL from the second cell (column 2)
          player_name <- NA_character_
          player_url <- NA_character_

          if(length(cells) >= 2) {
            # Look for the player profile link in column 2
            player_link <- cells[2] %>% rvest::html_nodes("a[href*='/profil/spieler/']")
            if(length(player_link) > 0) {
              # Get the first valid player link
              for(link in player_link) {
                href <- link %>% rvest::html_attr("href")
                if(!is.null(href) && grepl("/profil/spieler/", href)) {
                  player_url <- paste0(main_url, href)
                  player_name <- link %>% rvest::html_text() %>% stringr::str_squish()
                  if(!is.na(player_name) && player_name != "") {
                    break
                  }
                }
              }
            }
          }

          # Skip if no player name
          if(is.na(player_name) || player_name == "" || nchar(player_name) < 2) next

          # Extract position from column 5
          player_pos <- NA_character_
          if(length(cells) >= 5) {
            player_pos <- clean_text(cells[5] %>% rvest::html_text())
          }

          # Extract age from column 6
          player_age <- NA_real_
          if(length(cells) >= 6) {
            player_age <- extract_number(cells[6])
            if(player_age == 0) player_age <- NA_real_
          }

          # Extract nationality from the player's profile page
          nationality <- extract_nationality(player_url)

          # Extract stats based on column mapping from debug:
          # Col 8: In squad
          # Col 9: Appearances
          # Col 10: Goals
          # Col 11: Assists
          # Col 12: Yellow cards
          # Col 13: Second yellow cards
          # Col 14: Red cards
          # Col 15: Substitutions on
          # Col 16: Substitutions off
          # Col 18: Minutes played

          in_squad <- if(length(cells) >= 8) extract_number(cells[8]) else 0
          appearances <- if(length(cells) >= 9) extract_number(cells[9]) else 0
          goals <- if(length(cells) >= 10) extract_number(cells[10]) else 0
          assists <- if(length(cells) >= 11) extract_number(cells[11]) else 0
          yellow_cards <- if(length(cells) >= 12) extract_number(cells[12]) else 0
          second_yellow_cards <- if(length(cells) >= 13) extract_number(cells[13]) else 0
          red_cards <- if(length(cells) >= 14) extract_number(cells[14]) else 0
          subs_on <- if(length(cells) >= 15) extract_number(cells[15]) else 0
          subs_off <- if(length(cells) >= 16) extract_number(cells[16]) else 0

          # Minutes played - look in col 18 first (has apostrophe format)
          minutes_played <- NA_real_
          if(length(cells) >= 18) {
            minutes_text <- cells[18] %>% rvest::html_text() %>% stringr::str_squish()
            if(!is.na(minutes_text) && minutes_text != "" && minutes_text != "-") {
              minutes_clean <- minutes_text %>%
                gsub("\\.", "", .) %>%
                gsub("'", "", .) %>%
                gsub(",", "", .)
              minutes_num <- suppressWarnings(as.numeric(minutes_clean))
              if(!is.na(minutes_num) && minutes_num > 0) {
                minutes_played <- minutes_num
              }
            }
          }

          # If no minutes in col 18, try col 17
          if(is.na(minutes_played) && length(cells) >= 17) {
            minutes_text <- cells[17] %>% rvest::html_text() %>% stringr::str_squish()
            if(!is.na(minutes_text) && minutes_text != "" && minutes_text != "-") {
              # Skip if it looks like PPG (decimal between 0-3)
              minutes_num <- suppressWarnings(as.numeric(minutes_text))
              if(!is.na(minutes_num) && (minutes_num > 3 || minutes_num < 0.5)) {
                minutes_clean <- minutes_text %>%
                  gsub("\\.", "", .) %>%
                  gsub("'", "", .)
                minutes_num <- suppressWarnings(as.numeric(minutes_clean))
                if(!is.na(minutes_num) && minutes_num > 0) {
                  minutes_played <- minutes_num
                }
              }
            }
          }

          player_data_list[[i]] <- data.frame(
            team_name = team_name,
            league = league,
            country = country,
            player_name = player_name,
            player_url = player_url,
            player_pos = player_pos,
            player_age = player_age,
            nationality = nationality,
            in_squad = in_squad,
            appearances = appearances,
            goals = goals,
            assists = assists,
            yellow_cards = yellow_cards,
            second_yellow_cards = second_yellow_cards,
            red_cards = red_cards,
            substitutions_on = subs_on,
            substitutions_off = subs_off,
            minutes_played = minutes_played,
            stringsAsFactors = FALSE
          )
        }
      }

      # Combine all player data
      if(length(player_data_list) > 0) {
        team_data_df <- dplyr::bind_rows(player_data_list)

        # Remove duplicate rows
        if("player_url" %in% names(team_data_df) && !all(is.na(team_data_df$player_url))) {
          team_data_df <- team_data_df %>%
            dplyr::distinct(player_url, .keep_all = TRUE)
        }
      } else {
        team_data_df <- data.frame()
      }

    } else {
      team_data_df <- data.frame()
    }

    return(team_data_df)

  }

  # Create progress bar
  pb <- progress::progress_bar$new(total = length(team_url))

  # Handle both single URL and vector of URLs
  f_possibly <- purrr::possibly(each_squad_stats, otherwise = data.frame(), quiet = FALSE)

  result <- purrr::map_dfr(
    team_url,
    f_possibly
  )

  return(result)

}

# Test with Palmeiras URL
palmeiras_url <- "https://www.transfermarkt.com/sociedade-esportiva-palmeiras/startseite/verein/1023"
result <- tm_squad_stats_detailed(palmeiras_url)

# View the result
View(result)

# Test with multiple URLs
team_urls <- c(
  "https://www.transfermarkt.com/sociedade-esportiva-palmeiras/startseite/verein/1023",
  "https://www.transfermarkt.com/associacao-chapecoense-de-futebol/startseite/verein/17776"
)

result_multiple <- tm_squad_stats_detailed(team_urls)

"""Extração dados do campeonato paulista

"""

teste<-tm_squad_stats_detailed(urls_novas)

teste

write.csv(teste,'paulista.csv',row.names = FALSE)

"""Extração urls dos times do carioca

"""

carioca <- tm_league_team_urls(start_year = 2024, league_url = "https://www.transfermarkt.com/campeonato-carioca-taca-guanabara/teilnehmer/pokalwettbewerb/BRCG/saison_id/2024")

carioca

url_carioca<- gsub(
  "startseite",
  "leistungsdaten",
  carioca
)

url_carioca <- paste0(
  url_carioca,
  "/reldata/BRCG%262024/plus/1"
)

url_carioca

Dadoscarioca<-tm_squad_stats_detailed(url_carioca)

Dadoscarioca

"""Campeonato mineiro

"""

mineiro<- tm_league_team_urls(start_year = 2024, league_url = "https://www.transfermarkt.com/campeonato-mineiro/teilnehmer/pokalwettbewerb/BRCM/saison_id/2024")

url_mineiro<- gsub(
  "startseite",
  "leistungsdaten",
  mineiro
)

url_mineiro <- paste0(
  url_mineiro,
  "/reldata/BRCM%262024/plus/1"
)

url_mineiro

Dadosmineiro<-tm_squad_stats_detailed(url_mineiro)

Dadosmineiro

"""Campeonato Gaúcho"""

gaucho<-tm_league_team_urls(start_year = 2024, league_url = "https://www.transfermarkt.com/campeonato-gaucho/teilnehmer/pokalwettbewerb/BRRS/saison_id/2024")

url_gaucho<-gsub(
  "startseite",
  "leistungsdaten",
  gaucho
)

url_gaucho <- paste0(
  url_gaucho,
  "/reldata/BRRS%262024/plus/1"
)

url_gaucho

Dadosgaucho<-tm_squad_stats_detailed(url_gaucho)

Dadosgaucho

"""Campeonato Paranaense"""

parana<-tm_league_team_urls(start_year = 2024, league_url = "https://www.transfermarkt.com/campeonato-paranaense/teilnehmer/pokalwettbewerb/BRPR/saison_id/2024")

url_parana<-gsub(
  "startseite",
  "leistungsdaten",
  parana
)

url_parana <- paste0(
  url_parana,
  "/reldata/BRPR%262024/plus/1"
)

url_parana

Dadosparanaense<-tm_squad_stats_detailed(url_parana)

Dadosparanaense

"""Tentativa de criação de um csv único com todos os dados"""

todas_urls<- c(urls_novas,url_carioca,url_gaucho,url_mineiro,url_parana)

todas_urls

estaduais_2025<-tm_squad_stats_detailed(todas_urls)

estaduais_2025

write.csv(estaduais_2025,file='estaduais2025.csv',row.names = FALSE)

tm_player_market_values(todas_urls)